### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by perhansson** [meeg/hybrid#1]
I see the memory being used when running pellet_baseline go to about 2GB while running the loop and then increasing slightly while making plots after. This just scales with more input files which makes me think it's memory leak in the reader (as well). Should check that old baseline analysis that doesn't use my TI data bank hack.

**Comment by meeg** [comment]
I do see this in pelle_baseline, but I didn't notice it in meeg_all_tp, which is the only other script that runs over multiple EVIO files.

I also see some weird behavior in my code (my code segfaults because it sees events with bad data) that is probably coming from your changes to the EVIO reader. I don't have time to figure this out, but I'm putting this comment here so we don't forget.

**Comment by meeg** [comment]
I moved your TI bank stuff to a branch. Now meeg_all_tp works, and it uses the same amount of memory independent of the number of files I run over. So I think this must be a problem with your changes.

**Comment by perhansson** [comment]
Boring
