### ISSUE TITLE
TI stuff breaks stuff

### ISSUE THREAD

**Issue by meeg** [meeg/hybrid#2]
I do this:
../bin/meeg_all_tp -E -V hpssvt_006301.evio.0 -r -g0 -N100

I get this:
Found config/status bank 12 in length(4 1)
Done copy
"
cal_group_1 cal_level_1 cal_delay_2
"
Done
Found config/status bank 12 in length(4 1)
Done copy
"
cal_group_1 cal_level_1 cal_delay_2
"
Done
Event 0
found new hybrid: rce = 8, feb = 0, hyb = 2
found new hybrid: rce = 10, feb = 0, hyb = 1
found new hybrid: rce = 12, feb = 0, hyb = 0
found new hybrid: rce = 13, feb = 0, hyb = 3
found new hybrid: rce = 194, feb = 72, hyb = 1
found new hybrid: rce = 133, feb = 177, hyb = 2
Event 1000
found new hybrid: rce = 209, feb = 100, hyb = 2
found new hybrid: rce = 148, feb = 205, hyb = 3

 **\* Break **\* segmentation violation

It worked before I did a git pull to do my commit.

**Comment by perhansson** [comment]
I saw that today too. I'll work on it either Sun or Mon.

**Comment by perhansson** [comment]
Yeah, so I found some problems with the evio reader obviously. I made some
obvious fix which I think should remove at least one memory leak.

But still see the crash on that file and I'm digging into it. The idea is
that it should be agnostic of whether or not the TI data is there and the
"sample" and "count" should still make sense. When running that file I see
that it reads an RCE nr of 97 or something so that's obviously wrong. Can't
work more on it today but I'll continue tomorrow.

2015-11-06 19:44 GMT-08:00 Per Hansson per.hansson80@gmail.com:

> I saw that today too. I'll work on it either Sun or Mon.
> 
> Sent from my phone
>

**Comment by perhansson** [comment]
Hmmm, the switch to the new DataReadEvio needs TiTriggerEvent. I meant to
make it work with both (inheritance right) but it wasn't done correctly.

I updated your analysis using TiTriggerEvent and now it doesn't crash and
it plots stuff. Just pull the master branch.

Can you check if it looks right in your analysis? Jus I want to know if mem
leaks are gone, perhaps I'll run over a baseline to see at some point.

2015-11-08 14:53 GMT-08:00 Per Hansson per.hansson80@gmail.com:

> Yeah, so I found some problems with the evio reader obviously. I made some
> obvious fix which I think should remove at least one memory leak.
> 
> But still see the crash on that file and I'm digging into it. The idea is
> that it should be agnostic of whether or not the TI data is there and the
> "sample" and "count" should still make sense. When running that file I see
> that it reads an RCE nr of 97 or something so that's obviously wrong. Can't
> work more on it today but I'll continue tomorrow.
> 
> 2015-11-06 19:44 GMT-08:00 Per Hansson per.hansson80@gmail.com:
> 
> > I saw that today too. I'll work on it either Sun or Mon.
> > 
> > Sent from my phone
> >

**Comment by perhansson** [comment]
Closing this. Reopen if it's still broken.

**Comment by meeg** [comment]
Yeah, it's fine now. I wonder if the other scripts are broken now but they should be easy to fix. Thanks.

**Comment by perhansson** [comment]
I would bet using the current evio reader class needs the TiTriggerEvent class because of the way I attach TI info to that generic Data object. If there is no TI data in the svt bank it gets dummy nrs there I think. It'll throw of the TriggerEvent class either way. I can probably fix this with some thought.
